version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    links:
      - db
    volumes:
      - .:/usr/app
  db:
    image: mysql
    ports:
      - "3001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb: